/**
 * OrixAiCard
 * Streaming-ready card for displaying AI-generated content. Includes loading skeleton and copy button.
 * @orixakit/orix-ai-card
 */
"use client"

import * as React from "react"
import { OrixCard } from "@/components/ui/orix-card"
import { OrixButton } from "@/components/ui/orix-button"
import { Copy, Check } from "lucide-react"
import { cn } from "@/lib/utils"

export interface OrixAiCardProps {
  loading?: boolean
  content?: string
  model?: string
  onCopy?: () => void
  className?: string
}

export function OrixAiCard({
  loading = false,
  content = "",
  model = "claude",
  onCopy,
  className,
}: OrixAiCardProps) {
  const [copied, setCopied] = React.useState(false)

  const handleCopy = () => {
    if (content) {
      navigator.clipboard.writeText(content)
      setCopied(true)
      onCopy?.()
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <OrixCard
      title="AI Response"
      description={model && `Generated by ${model}`}
      className={className}
      footer={
        content && (
          <OrixButton
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            leftIcon={
              copied ? (
                <Check className="h-4 w-4" />
              ) : (
                <Copy className="h-4 w-4" />
              )
            }
          >
            {copied ? "Copied!" : "Copy"}
          </OrixButton>
        )
      }
    >
      {loading ? (
        <div className="space-y-3">
          <div className="h-4 bg-muted rounded animate-pulse w-3/4" />
          <div className="h-4 bg-muted rounded animate-pulse w-full" />
          <div className="h-4 bg-muted rounded animate-pulse w-5/6" />
        </div>
      ) : content ? (
        <div className="prose prose-sm dark:prose-invert max-w-none">
          <p className="text-sm leading-relaxed whitespace-pre-wrap">
            {content}
          </p>
        </div>
      ) : (
        <p className="text-sm text-muted-foreground italic">
          Waiting for response...
        </p>
      )}
    </OrixCard>
  )
}
